### ISSUE TITLE
Add Quran

### ISSUE THREAD

**Issue by bryanforbes** [bryanforbes/Erasmus#12]
Use https://alquran.cloud/api and create a cog + interface

**Comment by erkinalp** [comment]
How will this differ from IslamBot?

**Comment by erkinalp** [comment]
Please add non-Hafs Qur'ans too (IslamBot lacks this feature). There are more than 50 different Arabic versions of Quran.

**Comment by erkinalp** [comment]
alquran.cloud lacks those other Qurans

**Comment by bryanforbes** [comment]
I have decided the goal of Erasmus is to be a bot for Christian scriptures, creeds, and confessions. As such, the Quran is outside of that goal.
