### ISSUE TITLE
Slash command support

### ISSUE THREAD

**Issue by erkinalp** [bryanforbes/Erasmus#171]

**Comment by erkinalp** [comment]
https://discord.com/developers/docs/interactions/slash-commands

**Comment by erkinalp** [comment]
https://support.discord.com/hc/en-us/articles/4410940809111

**Comment by bryanforbes** [comment]
I'm currently in the process of adding slash commands. For now, I only have `/invite`, `/about`, and `/creed`. Let me know if you find any issues with these.

**Comment by bryanforbes** [comment]
All commands have been converted to slash commands
