### ISSUE TITLE
Not having to require $ for citing verses

### ISSUE THREAD

**Issue by GreggSchaffter** [bryanforbes/Erasmus#19]
I think being able to cite a verse without a particular syntax such as $ or calling the bot could be helpful, making it easier to cite verses in a discussion setting.

**Comment by minispeck** [comment]
there's a significant split of users who want implicit vs explicit. make an opt-in implicit setting per-user to allow this functionality. keep explicit the default

this way we can all choose what we want. for implicit users there should be a symbol to NOT trigger the verse quotes in case we want to list verses without them popping up.

**Comment by GreggSchaffter** [comment]
That's what I think could work.

**Comment by bryanforbes** [comment]
I'm not sure having it solely be an individual preference is the right thing, but I'm not sold on a server preference either. If I'm running a server, I don't want people coming in spamming my channels with their individual preferences of using implicit syntax. But then some server owners may not care.

**Comment by GreggSchaffter** [comment]
A channel on the Discord server could be used for that particular purpose.

**Comment by bryanforbes** [comment]
Since Discord has denied me the message content privileged intent, this will be irrelevant in two days. Closing.
