### ISSUE TITLE
Be able to quote on threads

### ISSUE THREAD

**Issue by gpontesss** [bryanforbes/Erasmus#245]
I have tried to quote verses on threads, but it doesn't seem to work. I'm not sure if there are any limitations on the discord API. If there's nothing that would unable it, I think it would be a cool feature.

I've looked into the issue and it seems that the beta version of `discord.py` supports it. but I guess it would hold until it's officially released, right?

**Comment by bryanforbes** [comment]
I've been updating the bot for Discord's bot changes and added this feature
