### ISSUE TITLE
Add NRSV Updated Edition

### ISSUE THREAD

**Issue by GitOffMyBack** [bryanforbes/Erasmus#269]
https://friendshippress.org/nrsv-updated-edition/

Thank you.

NRSV Updated Edition With Deuterocanonical and Apocryphal Books of the Old Testament
https://drive.google.com/file/d/1tM5zMwlVTw_4MFuPaMKtaDIZQJw6R0Yt/view?usp=sharing

**Comment by bryanforbes** [comment]
I have added this version as `$nrsvue` and `NRSVue`
